/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminRoleOrDepartment: typeof import('./src/components/AdminRoleOrDepartment.vue')['default']
    CreateRoleOrDepartment: typeof import('./src/components/CreateRoleOrDepartment.vue')['default']
    CreateUser: typeof import('./src/components/CreateUser.vue')['default']
    DataTableLogs: typeof import('./src/components/DataTableLogs.vue')['default']
    DataTableUser: typeof import('./src/components/DataTableUser.vue')['default']
    DisabledUsers: typeof import('./src/components/DisabledUsers.vue')['default']
    EditField: typeof import('./src/components/editField.vue')['default']
    EditUser: typeof import('./src/components/EditUser.vue')['default']
    FilterUser: typeof import('./src/components/FilterUser.vue')['default']
    FooterBar: typeof import('./src/components/FooterBar.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
